title: Theo Jones
description: Thoughts and Ideas

url: http://theojones.name
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html

social:
   github: theoj2
   twitter: Theo_Jones1
   email: theo@theojones.name

google_analytics: ""
